sudo: false
language: node_js
branches:
  only:
    - master
    - dev
node_js:
  - '8'
cache:
  directories:
  - node_modules
before_script:
  - npm install
  - npm test
script:
  - npm run build
deploy:
  provider: gae
  keyfile: distense-ui-8abca0329a10.json.enc
  project: distense-ui
  default: true
  skip_cleanup: true
  verbosity: debug
before_install:
  openssl aes-256-cbc -K $encrypted_54eebe5abc9c_key -iv $encrypted_54eebe5abc9c_iv -in distense-ui-8abca0329a10.json.enc -out distense-ui-8abca0329a10.json -d
